// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmgwdsrpqhqvnykzvjjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtZ3dkc3JwcWhxdm55a3p2amprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMzczNjAsImV4cCI6MjA3NDYxMzM2MH0.3Abdwzod4dy_ffE8Eqmxmq3sRrjmB8zZVwwALKp-sbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});